services:
  app:
    build:
      context: .
    ports:
      - "8000:8000"
    volumes:
      - ./manage_job_app:/manage_job_app
    command: ["uvicorn", "manage_job_app.main:app", "--host", "0.0.0.0", "--port", "8000"]
    environment:
      - DB_HOST=db
      - DB_NAME=manage_job_app_db
      - DB_USER=postgresdar
      - DB_PASSWORD=ioioIt1samem0n
    depends_on:
      - db
    networks:
      - backend
    container_name: app

  db:
    image: postgres:17.0-alpine3.20
    environment:
      - POSTGRES_DB=manage_job_app_db
      - POSTGRES_USER=postgresdar
      - POSTGRES_PASSWORD=ioioIt1samem0n
    networks:
      - backend
    container_name: db


networks:
  backend:
